url: http://grupofluxum.github.io
baseurl:

# Site settings
title: Grupo Fluxum
email: contato@grupofluxum.ga
description: "Grupo Fluxum - Para um mundo mais criativo, colaborativo e Open Source"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Fernando "ferox" dos Santos
  bio-id: 1
  pic: 1
  bio-1: Olá! Sou o Fernando, conhecido na interwebz como ferox e tenho 35 anos. Nasci em Floripa, ilha de bruxas, piratas e hackers cibernéticos. Sou aficionado por tecnologia e principalmente pelos computadores. Sou especialista em tecnologia Open Source. Em 2007 alcancei meu bachelor degree em Information Systems pela Universidade do Sul de Santa Catarina. Tenho formação em desenvolvimento de software com tecnologia Java. Em 2010 abri a freehammer - consulting & associates uma empresa de consultoria em soluções de código aberto. Tenho perfil facilitador. Com minhas habilidades de hacker facilito o empoderamento tecnológico.
  bio-2:
  bio-3:
  position1: Hackeador
  social:
    - title: linkedin
      url: https://br.linkedin.com/in/ferox
    - title: twitter
      url: https://twitter.com/hacker_ferox
    - title: github
      url: https://github.com/ferox

- name: Fabrício Noleto
  bio-id: 2
  pic: 2
  bio-1: Por vezes estrategicamente despretensioso, outras nem tanto, sigo com o meu jeito de empreender. Além do LED sou do Estúdio F/Noleto, trabalho para Fluxonomia 4D, Crie Futuros e Lala Deheinzelin.
  bio-2: Entre outras coisas, gosto de escrever sobre novas economias, educação autodirigida e comunicação. Estão no meu universo novas formas de trabalho, empreendedorismo digital e ferramentas web.
  bio-3: Em uma palavra, o que vim fazer aqui? transmutar. O que significa continuar criando a minha realidade e influenciar mais pessoas a fazerem o mesmo.

  
  position1: Jardineiro de Comunidades
  social:
    - title: facebook
      url: https://www.facebook.com/fabricio.castro.3348
    - title: medium
      url: https://medium.com/fabriciocastro
    - title: behance
      url: https://www.behance.net/fabriciocastro

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url: 

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Google services
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
